keys:
  - &amin_n550 age1dk40kh8vwhk7lf5qhwmsfh2twmj7gdrkynx20lh4lmar0z4kvqgshkm289
  - &amin_hp_work age1l64ytzuq5es89e4lgsvrj6tnhcgdq04wpfctj07xkdrc08utzchqg5l4pk
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *amin_n550
      - *amin_hp_work
