keys:
  - users:
      - &amin age16aftwyj928j8j6n2shuugdesppaz5p0r5evgg8888k0ygg70u4qsf7jc37
      - &amin_remote_work age18wwkg4v96ktu7pujcy3jc54j2gd0c3pt8vkup9qj2200dwr6vccsplhn5u
  - hosts:
      - &n550 age1dk40kh8vwhk7lf5qhwmsfh2twmj7gdrkynx20lh4lmar0z4kvqgshkm289
      - &hp_work age19ntyr90hwka356y4malera78wytrl6wr6eacwqppyu86eh4p6pdst4qkn4
      - &remote_work age1w9wfp2z6hnnt3yjy733eejy5qv894ml243z4ywyp3txpwvcfmdhqr4rnz5
creation_rules:
  - path_regex: secrets/default.yaml$
    key_groups:
      - age:
          - *amin
          - *n550
          - *hp_work
          - *remote_work
          - *amin_remote_work
