amin-passwd: ENC[AES256_GCM,data:rzvAZFzPB3Hrqew8,iv:LJ7HyfXdiiiDGVgpzyml1YGQc92Q8RKHmG/bRNrpg0I=,tag:SeAT1qq4LtozfIFNiZdiQQ==,type:str]
wakatime-api-key: ENC[AES256_GCM,data:b2jiy3dBkWgZJ5kZb8qEnTwmwu7hd2IJUBURtSTz3/NSIihgVvDJ6c4=,iv:HX0pbNF5ZiSJzU8GL2DHNaINzateyoLLzEex/hyaYmY=,tag:OjzKUqZjc8nq/PMPuFgJQQ==,type:str]
smug-kiz-operator: ENC[AES256_GCM,data:wv2vwyDnR1jpcJI+XaftCKTF45aW8+O99DUnOt8hyXJf3qIu42JDYa97YndJjqNrAGeDRkGZ5+tdk7WQI4opn8+/bJ6K2nRI3IcAgmvNBM81FwUz65dOMv/EMfqkQcdrw06QLCZ+m2CgPY8tvVCIEfli0Lckwh0kwqhN5aFS6IT0IvaepPulpp6dag0vsINwIXhtaZvnMD+gPkV6hMHDuQx8BLcP2DGNgv8Joh+U1GJW1EtWKhVBkTWpn1szIbPUAMv6X/lmJGSknmOO+IvzonkZOqoGKbZXxZPIZZNw3aaZSqTOI7uQYaTD/f3aLM2oMhaXVP+W/BPFttKtnQQutXlt7MRZZl52l6VYZ3Nri7uJ3OwSThBG7xD4DqlP4mH2G5uTAMBZMF5c3JD4/9K422DRWVwy1KPjaomPSJXx8RPMoh7AFfbcGPp4FZGEPU9mvDUCVpEiT5oj8QInty5hnrvybS4R0jSIjmAPGRmXkcCc3jO2bwiKMeafUt96EMCa4NIBwDPzCzE9THI1zz+DyVLo6IHx27AwF31b1sDt4agEhrGIMS0kSqueWM8N8kRaMjfWxYGHcHPUX72uhkAwbQi4pO2wBjGyDgM/RKHpDVgim4LfYZYuOAaUDao44yFyMfG7bBCt9eQttRm/c7ITcbbm94r/TQV9MTQhioZtMYRwoN+JnkLL5FuEAHFGYYqWsx/6etCKdEbY+mRfFE6nAAsWNDl8c8ftupkB+jFnepzIPZqqvsuprYxAHhXpFd59oI5XU0KHTnfQOY+X2Oy0AnFTMnJCUFGJFO/hxTsHl6AwA6Ib3KdlXpuZne3o5ZzLU6dnmEUTi7EY+jeOItiHAA==,iv:KWldA6a5dEYvUkYIKrucekYwfhtCvYwuBo4zTRLl3D0=,tag:JZuKW9uUu7fxU+uiiCbzUQ==,type:str]
sops:
    age:
        - recipient: age16aftwyj928j8j6n2shuugdesppaz5p0r5evgg8888k0ygg70u4qsf7jc37
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWGdxek9KbXZ5WTJsaHFR
            RHFVQzNhcjZyM20vQnNMdFNjOWp3SS9VTEg0ClkyRGhmVm9XYkFnSG9veG5yaDZl
            cUkzb0dCWXdiYytka3h0aE9SYkVYL1UKLS0tIHJjQndwMndRbmF1Wmd0cmw4ZzVx
            b2VZQzRTRWJEelhhSSsvQkYvMzFBWWMKbPiUNf4VPWPAn+jJCh2otR8nbEJ82xiM
            xW5gGzPxRRfWQdJ8HARZk3fMrmeMZXOGpDGwvJvAW3HcQiDhUjS+8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dk40kh8vwhk7lf5qhwmsfh2twmj7gdrkynx20lh4lmar0z4kvqgshkm289
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdlovc1JYTGZXOTZXeVNZ
            N1ZNUlcwNDFpQWpXbGtoOU8yMCtWMDdPYm1nClR0ZWI5SGhic0g0WDV4cGJpeEpJ
            TUI4ZGR5bzJPR2tKcmpQOW9LTTlBVGcKLS0tIEN4R0JTNDJVa29oL2piVDJFVldJ
            dEUxaEdJbk5RazNVSENJV3hSS0w3YjAKaWxmeiwoykNiMPNl5MDStl7vAcPDwBAB
            i+LMBjLQLmVfRXZF1cTv7+pdZp/FfN25kNGyHu0Cm37jnrJgJQo5fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19ntyr90hwka356y4malera78wytrl6wr6eacwqppyu86eh4p6pdst4qkn4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUlFhMDgrUkI5QmJmL0kx
            SmZVcWNIbkkyck1oa0VabkJVbEhtVSt2ajB3CkE0NXZZSDllNVdqRithQ3E1bzVx
            cnkxc29hb3JYSzJJZjZRbGdnTzV5MWcKLS0tIGJma3JxSVhuYmY4b1RKVExjNGdO
            TGpJSmRDMkRmbDFzY3JaVURJTjFPMFUKwZ2L/lTiP5hG56hhN7AO0G2cE/JU1iZv
            E5DRCof+aWKy92q0wqDHrMSJSci9nMi72XQ+TJhjPVaAHVgayXOfsg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w9wfp2z6hnnt3yjy733eejy5qv894ml243z4ywyp3txpwvcfmdhqr4rnz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdnlqUmpwTzA1K0FSbVds
            dzg3WGp3MHdCNlF5M2xVanZ5UVlJblMwdzFJCmUxR3FzeGdxSFFrWEJQVDJGRVFD
            eFZJUU00eGwydHhrMlRjZVgvSE1EUGMKLS0tIHdRVG50NU9uNHVxK2JUK1NHSnNk
            cGR0bVpVd3hSKzJveURzNXo0YXAwSXcKKpv7GxkJGlhK5Eg9JsWIrALIbM3CILnq
            lEZrmzySblPL+vN9pnv0orkpvhTI7o9lnnKewIVA+Po/y0BCCxfu7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18wwkg4v96ktu7pujcy3jc54j2gd0c3pt8vkup9qj2200dwr6vccsplhn5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNDRnRVNsUkM2TWhNbmNW
            di9YL2NTVFh3eUtiR29ONUxXa0hhOFJINkZFCnhnd2ZjNiswc08rUHh3RXlFazRL
            ejY0MXNxZVVna2Qxd1pVQWhkeHhNZTAKLS0tIDlBSjR1VHVuNU45dUFvMGFCSVFU
            OFM0RG9sNFJOMlM2MHhjZUlPQWdydjgK9s2qej3QFYuBWSsU9nWrn8rwnxeWCobV
            nPlwx5unitj3Up5MbT6YfAuw5zX1NTMGgkZ822N/vPTG6hkrFEdZDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T14:04:14Z"
    mac: ENC[AES256_GCM,data:PSHbbLDpfUWc86SElDvHp/UUGowZg0KEXnx7uVqqYSkpmDzwoEGbDpTrrevEcujrN/07kxX6iB2nA780mfcPddS8yaKg78h/heHNyr8Lq52fAqjG+wvo4rCs79YJM921Lu0R+f0G/4YWa+LkKqnuoX4GTwAgU29Is4C7w++KnvQ=,iv:DR1V62RdAdIBReEdl4KlQxNg0qgg3BZEI4lN94Asxsk=,tag:t/ykeJsQgQu7EZ2THufKSg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
