amin-passwd: ENC[AES256_GCM,data:T9KURdyAt25JCSs=,iv:qEFgXrKdE+WgpJ2wLEel5m4E3ISyVvsny6EbbvOLd0Y=,tag:nTLS3tOwuvs+lqfgWqjBlw==,type:str]
wakatime-api-key: ENC[AES256_GCM,data:Sa/fdDGO/S/asSUxbhoRXoTyhU9NK6jQ208a1eLS7oXgPkoWU4ZM3fM=,iv:HX0pbNF5ZiSJzU8GL2DHNaINzateyoLLzEex/hyaYmY=,tag:1LHpP5yivIhrL8b0+QY35w==,type:str]
sops:
    age:
        - recipient: age16aftwyj928j8j6n2shuugdesppaz5p0r5evgg8888k0ygg70u4qsf7jc37
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaDJyd3hsZW1XRmVWUngv
            clRRUS9xeU5FUC9TNjR1Zmd1bVFzQ2M0STFjCm1BQmc0Zy9JQjU5UkE0MHRid2Fr
            dzFVMzdDdlVGUzRIZFdPSVpGdmU4aVEKLS0tIDdtY3lIbmdXTDIrOExsbnBaMHpa
            RDMzbmFrNnRXWVgxUXU5SlMvKzhXT0UKM8W7oetYFeA6/NdNqQ6pRM6kZ4BfMTsO
            BCtfF1ZpvgA4bGUWicBJa1aqkiEwYgBroNCKZY9gfOxebdzY80f/gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dk40kh8vwhk7lf5qhwmsfh2twmj7gdrkynx20lh4lmar0z4kvqgshkm289
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV0pvaENsRndwLzFvMDNm
            RXFvM0QzNWdxU295TWpXZWNTK2k5NDRDL0dnCjVhN1N0d3RNOHFuU3B5cUd1ajF1
            VktSekUxYThIOGplSXpuVStGWHRmUEUKLS0tIDlDYUtJUDV0eC9uNzlhRDB0eTJP
            cDFSVi9rMGdzalRVUjBJNnVkU1p1bzQK3JKj7NzXebMP0d5Mw33s9d4gBmjh3VsR
            QkMa063fmUWqKcQUk0Q1KmB0tHmwJGk/ILZJivP291jVWPZ8zUhEMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19ntyr90hwka356y4malera78wytrl6wr6eacwqppyu86eh4p6pdst4qkn4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVHQ1RitBUlNCdUpHMGha
            UjV4L3pNYmpNaGRMSzMzNnNGQnBtaDZSSzJzCnNhVW8yd3N3blFNaDR0bmIzMXkv
            Z2JSYXg4SFZ0OE0vSERxM0dtL3NXZUkKLS0tIGEyQytvT213Z1l5UUJCcmpoZmdM
            QkFlY2NLS0QvYmx3LzVuRVZNNm0za2MKX5riI7f89wyKZ5SEI86SriQTg9nRenYI
            3O/l+0m5Ie4D6fa+u2f+IVTWUJLUuBj1g4dMJb257tth71Ag3rUPJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age125lr8v7xkvv7el6uk7hr75czqsk7m7px7sz9xcgtjy3mjd8lgcaqcwpxsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncHNFR2F4MkIyNjZBSks2
            RE41UlQ1WTZ6ZEpaOXJCS1VmUWJVcng1Tml3CmVhcEs1azUydUxwMFdSaS83YzVz
            Znc5eHIyVVlOeGE5RXlqa0o5N21JblkKLS0tIEREcVNyaGdrRmowZ3pyVEtWWmNy
            OGIzWTVFRlJZNTQvRXA5aEVRV2dUV1kK23I4DaQ+Bkhv8DLPHsvIQnzC/giIf4mq
            mYrxYhqy/wpH5PeGNfWaFrjqX35YObwBR3vPU3a0q+KPwmQpwtlcZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T14:25:18Z"
    mac: ENC[AES256_GCM,data:7CAEFYcb7hcVyR55AFRYfWZ6vbNCZJ58+yfMNQg5odOTTiKJMgas9MAMUnKD5GdXn8T9ACQfcfQR2Og68mWXF5BtSfiHeGjcY4j0zCt8rNFMTbJyhTL9nE1a2Y6mkuUMevQbSzq+iFqv2QJWrpudXX4qMZxH9bKiduG5KGrwes4=,iv:bHJkzFfqwM+8ZmpNq8K/H74hUb/IFWzMumikvftlahI=,tag:huq/52xWwACTSBvYida4DA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
