amin-passwd: ENC[AES256_GCM,data:kmt5hv2URLuBL5c=,iv:WRkjfpf2XZJRdpu3AIlgkprAbqirVIXzuD6QoEL95Mo=,tag:cFVNzx2/AkZpUIUKgztzKQ==,type:str]
wakatime-api-key: ENC[AES256_GCM,data:rDia2tl/,iv:sZQXpc6RzVLYHcvijIOZODzUWB/h/9dhG0ysT3e/u6I=,tag:HUIBFsjW0Hfuj8LWgNxAuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dk40kh8vwhk7lf5qhwmsfh2twmj7gdrkynx20lh4lmar0z4kvqgshkm289
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S3lOWVRUS0JOYUtaS2pj
            TGhucFBKNlAxclFCRytJc1ZaN2pDNGdQa21JCjdZeUpIYnE0S3pGVnRuRTFBK2li
            NzhIbVl2MFhDZXlaU1dBL3VwNENqQmsKLS0tIGpVWHArbXlYdVdmeUR5OE9wclBr
            R3YxRkFzZXFxMHNidDBLQWovL3MweEkKexkLglc3q+47kjPibrAg3Jcwu8n/BSQS
            O9Nd1KhWPe6GPiZkOyHKjOQl7I2lOGlqIu/hw10y7thICwSGVkUy0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l64ytzuq5es89e4lgsvrj6tnhcgdq04wpfctj07xkdrc08utzchqg5l4pk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabW52RzZCenNibTJmR1d6
            cDBlUnJiYVg0bmFDSDluWjRWZ2ZxNXc4ZlgwCmczeDluQjdXVGxZVEVibW9INGsw
            ekg0SHRsbFZSMkxFSk1NeVdJSzlvNjAKLS0tIDU1WFJVeDdOVjZYR0t0WVUrS0Jt
            VUQwVzhYNDJaQUhDV2pHVWdhdUt3TnMKXpLsos0ZGvLyfznJCnpkFCrMG7WHqPJM
            MdVj0G6umFyu3wEDtS11eLrsefLCFP5xT9/fDG0vVJXu6VdIlS2uTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T13:23:24Z"
    mac: ENC[AES256_GCM,data:RvxRHDMzUMs+tPSRGtdTNweTn5icuaGnO8o5lx+2wz6JVsn4FbGkOrsyLHmPLuRIwHr3JEwgjbpvB8J4+H1tKCa65MXTPYkmiQTDF8BAK18fphan/mcLi4xttssgVdsUu3qO2ETKPczU7ks+70TAD3TpjPjg26qrLVFxBnCjOAE=,iv:a3u4ulJF+UkStt/WODr7snnXwXABpRZH00+wrZzRYlE=,tag:J7T/MEliy7WARFdJ0/YLaQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
