amin-passwd: ENC[AES256_GCM,data:xhAD4SHw8GTJH8bE,iv:LJ7HyfXdiiiDGVgpzyml1YGQc92Q8RKHmG/bRNrpg0I=,tag:86C0pLWjycF9QnH1boOdNg==,type:str]
wakatime-api-key: ENC[AES256_GCM,data:o2KNfFjIc4sUgfUHEZ8aicAr+prPhxE+66CwZ2yJlhKQeOILPRxRADY=,iv:HX0pbNF5ZiSJzU8GL2DHNaINzateyoLLzEex/hyaYmY=,tag:dxjrT9UyW+u3onrXuznFPQ==,type:str]
smug-kiz-operator: ENC[AES256_GCM,data:/ODb1d29JxKW+/6GIqlVGo2NaUQsvX1d3uOmwM5wEKADmmw90Pm6wFQKcQcliAsYKQHwATEefJCwxz3p1LbsFrqIu7ZVOc/FzYMaCCP0GgmpuCovJOZk1NwVWZXACf2hAvfRhBBHPi/jc7OvX457dNdp4QofenOtj/P0CJImeR59ZQp/9J5IFJCt1gC78IAMSLm7WroaSe3qO/ho61SS4HjG8RD0lbgqfrc4/3CIjq4JDtsENegyDzz5mK/DOQseA4fQLp6akyzldfwnfB6u7GBk8qTVhFrvw8t+JJESEvPsBvs5uU1EKtSQsbZEXdYgYKTpRsYROb6AiuK9xCqmlLoDycSVJWCD0DKmRG9/yBT1kDnGleVQTd0e70r+faVf6LpaO6c+jcNdfczTTh9C/BrlvQPpK6QfizsxUhQrUn2mnXmOxBDVkTqU+P3A8lC01OlILyra0hXKHue9BH5LRd5/5T4zqc9qDnoX3jdbIUDZH0Z/VNF5sRDxfOlQc1fyz6QXQ8bYCBtFQ18BBj54pDgeL99dBYte3jlgDsdlr1HaS2ZbjcmpYbrdWU4KMV9Qe8SfJU6RRl/JqJmNX6bcnkVzXwZONmzpWS8Njc7mxrweufau+c4iwS90AD9UIrcwFZz9hNZIc/LhE+Gc2qYsziWmQzCJTepZrxLwpdQEDIrBTHGEPprySEBtGtfCnV+8ebxp6G91oIXUTr19nODKrIEZItVHFM99TvAtJIA5EYUfVypt9YgjMizkyoima0WalljQpJbyZk3Khhr1gdk65kHxWs8KgBYr4wlIWLAVOGQaCH29j49bWbTA4QNOLC4IUfoTJXyCnEc27z6hrC36lg==,iv:KWldA6a5dEYvUkYIKrucekYwfhtCvYwuBo4zTRLl3D0=,tag:GZNU4JQ8izwA5UxHhfjdCg==,type:str]
sops:
    age:
        - recipient: age16aftwyj928j8j6n2shuugdesppaz5p0r5evgg8888k0ygg70u4qsf7jc37
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa1dHdmd2c0oyWU82V01l
            TWI3NTRDc1I1cXNRWXRwMXRJMStUNktFT1JRCmltRU16TGluUEpQc3VQa3hHWXY4
            NzViWUFWR1gvU21pNXU4SnJZY1FZV1UKLS0tIGQyamplNmRMMGt3N0gveDZxOFNH
            VTRHVFk3eldrN2tkd2FFSmc4WXdObUEKmOEBnqN05pgwhi9E1lb4xJL+sr2NGe30
            FQzh/55pldiE8XwV43N4GB/BBz/LrOV47Jihy8bR8CR2tJhsK554Ug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dk40kh8vwhk7lf5qhwmsfh2twmj7gdrkynx20lh4lmar0z4kvqgshkm289
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQkhBWkJPbC9nKzFtZWcv
            R3RHZnlFQzBkVmFlWlNRZVo3Q2REM0pTY1ZBCnJGUUtkU0F4WEV4OGRBUjdhVVBL
            K1drUTlUc0NwMHg2dVJSQXFOeHZlWk0KLS0tIENUYVVLbjRzaXBGZ3lBNTByblY0
            NHZRU1R3Q1NYYXVlRlZ0a3NrNmlRNjgK0rnA/hRL+CtGSODbakQnENv5ba3HH5Es
            8D6t5/cdgJ8nVrtYMLEPbpSVZS99iQ3UkW1ufA7KsoOUUT7VTGjqeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19ntyr90hwka356y4malera78wytrl6wr6eacwqppyu86eh4p6pdst4qkn4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbVlXeFNYZzVLQldWWUUw
            NncvTmFQU1pQNkpCUFBVMkorNkMxNTZiRkJnCkRISE1GLzh1VWJEV2xmalVqYkkv
            Yit6OEl4T1JGbFNqMnFKejlWZ1lXRXMKLS0tIEhsQ1BDa21RTkQzSi9FdzZiTEg0
            TnAreEN3cDNROUtidDFubTdEdzBBdXcKCqoaEFM2kyTWdbd0sZkpeo0ZNME1pxCr
            0xiUN/JPJzxx7ZxM3KTuF1D8BOisUIiIEa2SZQ2IEiSAfcBoXnupog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w9wfp2z6hnnt3yjy733eejy5qv894ml243z4ywyp3txpwvcfmdhqr4rnz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaXE3Z2R6OUhTeU9wVEli
            UUp2NG8rY2I4NzB3alV0cjNxT3hYblpCekh3CmUxQldhRC9tbW1LN2pQdWFFOGdi
            QU5qS252OTczdFdveGYxTXdkQXdEYXcKLS0tIFFoK1IxcXgrY0RCZ0xtYlRNYWNV
            L2ZHNTBUNy9nSnhFTGJ3RWdOdlhTZ2sKDZWzfqlbMMdjQp+sz5mkLLOXfB1cCpWy
            4GbraOJ+tal17xhfY17jy8X4z/TL35vE379zGsC/HxcFVyAVcvpbSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18wwkg4v96ktu7pujcy3jc54j2gd0c3pt8vkup9qj2200dwr6vccsplhn5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdjR0WFpUN0JJNERMRlM5
            M1BxNkE0YWdLOGRlbnpTaGxaV0xucDE5anlZCmVhc21LZ05DV3Ntekx3ZjA5OXg1
            cE51eVE2aU5jWkl3SkQ5SVEwTzNIMDAKLS0tIFgzb3ByOXdFdVI4azFGRm9uOXpL
            dWxVVWNBMnlrZDBmd0ZpQ3JRVmlXMVUKQpn4JEqp+kGaZNyuHs0+7IcIX6Ifr5By
            stHN1ICHary2WgSv43a38c4hC+fZ1o0By9ubHYRvKzo3+quNvPXl+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jnvlfq8cyenrhxcfu4m67xs0uvxv8gvaf3dev385t5zdwvepm9zqm02mgv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeWJWVmJkSVlIR0NsaHN5
            SThnYVA3Sm83RjJxUVNPcXVWRy9SSmVhM0JRClBDQ01uaDdycVJ2WE5GeGN5VGJt
            WU1KNjc1cnJFcm1lWVRSRG5nazh2Q0EKLS0tIEl6ejkzWFo5WlBTTCtiVTBMNkJx
            eUoyZFRXeUNhRys0d1BxaEZMZ0MyQ1EKjdNFBTVscPIAs4Nur8ZGJOFnoXZroo3j
            sqOvH/qA2rQW9WKr3/IWVuYWkV4Nqz6fGRD44xgYKzzoIRvGd7GmUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T14:10:21Z"
    mac: ENC[AES256_GCM,data:k8AkaU8jvFgpfETs3W89Dur/aGfdF+eoSqZ/ZA1rRB3F/YLv6o24AZrP/t6h4FXkAHUpz+rttSwcLr3UAuB4BducJmoCH3xAYRd5zAYvBYd1ysypKANlSwEkIxNKXYygJm8LqGWDny8uihgvtmQcNGRpaIzyqC2bu4QkUApmPVE=,iv:rR9u1LetXyiswjYZ4UFOkeahHkiAXn7EIP3tVed+BG8=,tag:bPVjPigdZCQEIFWGXjoZvQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
