amin-passwd: ENC[AES256_GCM,data:IluRoWU0mB7K9XB5,iv:LJ7HyfXdiiiDGVgpzyml1YGQc92Q8RKHmG/bRNrpg0I=,tag:KjV+2/qlseTED/3AJ66ndw==,type:str]
wakatime-api-key: ENC[AES256_GCM,data:WXS/qEiJBDOd/CQsjCfeeNxxu6L++BmfVO3EglsUxlmnxWItaqZ9vxA=,iv:HX0pbNF5ZiSJzU8GL2DHNaINzateyoLLzEex/hyaYmY=,tag:+yNovrnCh61YXV2JiT1YZg==,type:str]
smug-kiz-operator: ENC[AES256_GCM,data:78gOpNNuJvTtk1CfYK/rPoLPi8lp4rLTyHaVGmxb9wYMGjF723gbVFyxL6eG9XPwVN6tixQiFkQkgS9UYRKgfRDuloihQBTFlarsjR/7UagidgNTwVryFaDN5coCVV4iQrVsF7KhTjiSI3UI3B/OuDm0WIjLEXforAuzrzHnxeJS+rK3righ/+oAlF/tVGhV/xjLFVmtWAnCi83AEvLz4uF71L6d3GTFIvErb1pygf2mkkjVmQirE6+HucRraf+SS2sHHmYZ+pROAE/5Q1l/9mFDNmxvNMSV70oUmJa3h9vZFkwWncLIKF40m5Jupq+5dxpnfuiUdhbv1X7gyJvcpuPXNzwa/V9S+7ra0zxKX1VLQFUdW9ebtwj3WpVVx1OggWenMcextJiYWIB0dbAFDm2sGpbA5dAM+t6XkhnRywuIcoucZ34ZHee0wajmVPadt8r78X2w8d2q5El7csFBipbFbpRqQJYpvvaHNI/rUaUsuYfk4tEFbmc05g4oXtKXWjWvZbIOLcBLJbLLBb6m2gjCGskVS+/G5w5n/PAfFCUZ+qWPqzNHg3/PuujUNESI/M4Osdm9P3TFhK6Ur/NG4iH+9bDngeYnj/vCfLRRjLmit98pgEWL4lBXIBhEpHVneoicAnDw1uoMQ2F1I9vHYXf6zMZyTJEiHDKMEya0FXE9ip50ZE8ozFSY+T/NfNtNjWvUNS4dKLPuAR9/wLq+yo0/jXal9bkJ5C/4BbogiHML3WnpyToyWxwIxL7cK1IP25/0hEPdgiHMElR2DUKpgb5sdOCjJPHNmn4Xzb+NoB+HsxJveSf929iJV/XVUFjn71Fd7ApoRaGCT/D3kXII1Q==,iv:KWldA6a5dEYvUkYIKrucekYwfhtCvYwuBo4zTRLl3D0=,tag:K5cRe+t8HRcEThJwDM9ODQ==,type:str]
sops:
    age:
        - recipient: age16aftwyj928j8j6n2shuugdesppaz5p0r5evgg8888k0ygg70u4qsf7jc37
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZlYramtwQStLL2JuSUdv
            VXdPTTFLTVlxUlZtS1VwcCsrUU1RZUxwSURrCk9sZUxUVFU1eW5RNUVkU1FhNHJH
            ZW95cDZhbnlMRDlRR0lIM01IckprK2cKLS0tIHhvWFpuaWp6MlZCaWc3ZGtqMDNU
            cEtnZ2E0cEtVN2VzdFZsZy9iWHE2TjAK/UEJv5MB5sChov/UEjZFW6/9zY20lxoJ
            JHhezZxkWRWfprKU6oCZX68WSeqf13Bx5iYeGtoHCdHPPBcsAa4oWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dk40kh8vwhk7lf5qhwmsfh2twmj7gdrkynx20lh4lmar0z4kvqgshkm289
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWUhBc0NrSjdoYUFkR3Q2
            cUFjS1dUZnUwUmJ0cWFkVkpyVS92N3pyU3lRCnU5L0gvM3ZqRk40WjhVV3dDVU9s
            MFNNc1VyVlphV1BBOVNMcjFjVnBXMTgKLS0tIDRoWitPb3ZkWFdCVnNLVTVoTEV6
            a3Bna0pPQmh1TXhJWTNXaXJsd1hZcUUKudQfipNq31Do6UFy7Fy2VIjOR74vwES2
            gODD+7s1xhzEf90IGcV1St3jwmncuPDtULNbwDJZVOT5imPWYqpm9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19ntyr90hwka356y4malera78wytrl6wr6eacwqppyu86eh4p6pdst4qkn4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURjRqLy9qQXVpWFBKNmtG
            ZHREN3V3RW1DamFHZDlWcVpRa3labGNiVVVnCnBpUUpnUXhsS0M2dXJHbDNUNS9Z
            eVlMSmlwR1Vpa0U1Slk5YVRhcDNMOFUKLS0tIFEwSHB5ZFFQdGtGcEs2YVpXMVh3
            LzBkOG1ROHkzSEhDWGJDY3RibmxheDQKJKqvHkx8v7ZCCbT1IogOKsKcoD0kmPME
            hxBNBaracwOjm4DJUAENBaeG9EFzK1tuByE4HDfpuuPOX7rGUF0spQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w9wfp2z6hnnt3yjy733eejy5qv894ml243z4ywyp3txpwvcfmdhqr4rnz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2elJlblllUEZNYTBjNnEz
            cWtnM29kbk91NnFKL0NFUHdLd2hoOUtLbFNFCmRqZkdLZWU1SmxyZ3pRdG5mMEow
            Y05ZaUhKZVBiTzJPalVnUzRqRDlXVkUKLS0tIGdwQWpsb2R2dWhrRmRPdHdiNTNi
            ZDJQcDY2NGtmQXdya1o2TTduaTV1QzQKvPM2CZngKYGSFb0LMMVufOzK4buUMUaM
            PuOkBpmB4RDqhWbEe/ns4vehVEiaHK4pIwyhixCT5iGQF9CiXhgiDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18wwkg4v96ktu7pujcy3jc54j2gd0c3pt8vkup9qj2200dwr6vccsplhn5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUmZRS2M4ZmlTaDZtc29o
            M29Ld05HSlk3d1hTZ1FoUDNGM1BKQno0MjJjCkxKQjk3S3dUMkVTRzJ5Z1luaE80
            T1RkeUd0N3R4RE9SM3k1ZVFqcHRweEkKLS0tIFVuQytOaFIxNDdMNTlIclRybmJl
            b0NaVVpTdUJDWVZ4dmVuQUpzUjkvaWMKRDpKo/hH+eOzMWsWOT3gAmkBTvMu9n9S
            DIer4bZngKByR72/pyH/EgmrwPLhIYE5RX4zyCHswEYkhjsVZ0X78A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T17:20:07Z"
    mac: ENC[AES256_GCM,data:rQQ7BuSDnlMqildob00psmMRz4/wDjH81RXwrrPoaxYZy/QWZuzMrNTUMUDtHfyM/adqxV0yHyhg+8Ppzr9yZzBDQH/tPMHcD8Upt//GmHCbwwb7+1M52jKpKHcmrYnayojzqsp+zkkJIDt21sjT4WkSzjy7Q6zbCoPC1MinPzo=,iv:SWqCANJjGEszwMieEggWsR1TIuvwqTeIC+61XZPrulA=,tag:h78ADh/oipQwIK55jMzEUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
