n550-amin-passwd: ENC[AES256_GCM,data:/SX5INGI1+60V6o=,iv:OGHfTf4pOeU623uw0PbHcUorE7BbJ9Z43V//9sMpfVk=,tag:S0XUnQv27TPM3yfiaC5o2g==,type:str]
wakatime-api-key: ENC[AES256_GCM,data:WsY/RgadbBu/dVDIyof+WsN+QJi7+H1y8+tdM/QARhwfuqtsR2egEvE=,iv:iTjoqDrUtqHkYjuhHg46PRH51U262ogZAw7bwTMCnvA=,tag:hc0vkR2S8hZazrqgrU+UZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dk40kh8vwhk7lf5qhwmsfh2twmj7gdrkynx20lh4lmar0z4kvqgshkm289
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZFFOQVJ0VTM2L1FTbE4r
            bGpTZ3NONDIwbFJSVXpGUHBsUzlqa0U2d0FNCjBRVXZuN2hCRmh2eW8xazZ4aUZV
            THFiQWNjNTczejU3S0Flby9zaE9QdWsKLS0tIGxoa25LQmlNOUJ0YXpIVEhmYWxm
            U2RTa0x1dFhscWtKUEV6WmNJTTcxUzgK0UuPOPytJY3KSa7qiYdtpKjglPiZmq0H
            dqgEfx7W3VV4jJYG60HeJHgrnFR4K4xX0Pts3YofJx8HYF1grF8jTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T17:59:56Z"
    mac: ENC[AES256_GCM,data:OXjESZXH7JEtrsN8A+HRDcN5goSvqYhLzJS1+mEil2qbh7MYI415jr2x3ejQqu3IGA31DIWarK3biY2mnEnLa7zFRmGKPhvAGAZvAAYR77M1I4mFhOZk7C0zNiDv/DDCi44fcOSZNtIe3aIzHgqpR4HrvbLgQhM6Kf7/Lln3kUY=,iv:/uSwK0z6RH4gWlfzuAPUIm8juK2JgnoM/oy7dwNmljc=,tag:cjcMpy/qBP+tF+4uv6zKEw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
