amin-passwd: ENC[AES256_GCM,data:KO2a5uPTsV5KpbE=,iv:qEFgXrKdE+WgpJ2wLEel5m4E3ISyVvsny6EbbvOLd0Y=,tag:SQwoNY1pPlVUs8EXbQgrfg==,type:str]
wakatime-api-key: ENC[AES256_GCM,data:/0FXNlV+KY9dKU7Er2hIukfuWHywmZ0fi+tkqal6GU+7RkhqAKtgiEo=,iv:HX0pbNF5ZiSJzU8GL2DHNaINzateyoLLzEex/hyaYmY=,tag:zHtOLraWOgys3E/iXxBTwQ==,type:str]
sops:
    age:
        - recipient: age16aftwyj928j8j6n2shuugdesppaz5p0r5evgg8888k0ygg70u4qsf7jc37
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MDdhb1diM0txSFJaU2JC
            UStWMjZTM01nd1ZsWEw3a2g3dzFpZVNZTmhJClBmQUF4UVRvSzlKcCtZT1B3alNa
            L0tXdmlWK3JzZ2cxbmc3UjdrSzBhWFUKLS0tIHAzaEQ2dkNGNFRvKzdPbHp5ejRv
            MEsrZGg0Y3NTM1B0R2FkUUxVWVhuSXcKE6vldjo9Zvp0mYoSpHGQ8lqnlMjT9ZkN
            p07jgcFLPXg2fKHrexJDl9EK64Or2yNJhcgfXF39HmQLqDDwlW2ifw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dk40kh8vwhk7lf5qhwmsfh2twmj7gdrkynx20lh4lmar0z4kvqgshkm289
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRzRWYjBFZ1lBcGpqbjRR
            UWR3R3d0OWM3dFk5VnlKODBDMERxR2tVRGhFCjF1NHN4ZXpPM25iY1dmeXlHL083
            N1E1T2pPZTlzdDNJdXUrUnQ3OHNUNm8KLS0tIEpvMmwxeGNIN3pCeUQyL1pOTmN4
            Z1BXcWhzV2ZkWjlBbHM1WnMreEZWbkEKpCaElAg/XQ8PV5GoiPxcD6gX6gybfVpb
            o1pqxjZceDUgBJ6JOpgW++QvE4+O2jccTqUBuClswqb6O6YiLIqLxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19ntyr90hwka356y4malera78wytrl6wr6eacwqppyu86eh4p6pdst4qkn4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWjc4Q1RaODRvcnpyRmlW
            Sk00OHBlSmorWE5tZlRRMjFsVGMrdE9GVFZNCklJOFJ6RTNTTVNtNUhQdDgyQXpD
            RTJJOTU4MWg1dTcvUkMzSXJSQjQ4WlkKLS0tIHRpNXNxUHFDYXpEd21pVEwzY3pj
            eUZIM0UxclJVeU1QeG1CS3AwMnhmV1UKd4JHszNKxoocSfi/7gJAvrPuLqv4Wsn3
            vKGj2yYejw4bzADZcdrDzJGvC7jzh43WxN4muE8NHR3wykQG0GgYig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age125lr8v7xkvv7el6uk7hr75czqsk7m7px7sz9xcgtjy3mjd8lgcaqcwpxsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSHZiZE54dW8xQUs2U1dV
            b0pJeGZVRDZwSWdaUndUaDdaRS9CL20xTWxZCjlxMWNoQVBIMHBTMkM5amZWZVJ2
            ZUZVcFlaRG1QL3N6Y2p1NkhsSnlackUKLS0tIGNtN28yZE4rWkZkRkhBbFY0UmVD
            Yko1bUgyeUhsUmNpMUp5UXo2MDdham8KUSG7ELuZmAn/IV4M/vGCQ21KChK+gGEz
            SGd022ofXQ4RHmhT3qbAKOaoPNTj59bcyFbsLfgwgEqm2LW6pM9qRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T16:28:06Z"
    mac: ENC[AES256_GCM,data:P0T6q1s2m16LDDMBiYsZWBboE9MBqXZNcbl7C/UUalQHBVRCwXN+4UNY3+dZ6Vvhwxmge5nCJa2oXmIdUTiVTItWo4B1Ofi6mEa4EvylC27UiGsk8ZcgIW6rm0UrK88yo7Geu0v2tghVOZ8pniSEOY033WZgPHCO3X008DOw+X0=,iv:ftQAs5J5oFfkSKKeYdlNpQ1QKazou7EIqJu/ulWg+Bw=,tag:jB4p9ZbHiI1fmXjwWhHaYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
