amin-passwd: ENC[AES256_GCM,data:xhAD4SHw8GTJH8bE,iv:LJ7HyfXdiiiDGVgpzyml1YGQc92Q8RKHmG/bRNrpg0I=,tag:86C0pLWjycF9QnH1boOdNg==,type:str]
wakatime-api-key: ENC[AES256_GCM,data:o2KNfFjIc4sUgfUHEZ8aicAr+prPhxE+66CwZ2yJlhKQeOILPRxRADY=,iv:HX0pbNF5ZiSJzU8GL2DHNaINzateyoLLzEex/hyaYmY=,tag:dxjrT9UyW+u3onrXuznFPQ==,type:str]
smug-kiz-operator: ENC[AES256_GCM,data:/ODb1d29JxKW+/6GIqlVGo2NaUQsvX1d3uOmwM5wEKADmmw90Pm6wFQKcQcliAsYKQHwATEefJCwxz3p1LbsFrqIu7ZVOc/FzYMaCCP0GgmpuCovJOZk1NwVWZXACf2hAvfRhBBHPi/jc7OvX457dNdp4QofenOtj/P0CJImeR59ZQp/9J5IFJCt1gC78IAMSLm7WroaSe3qO/ho61SS4HjG8RD0lbgqfrc4/3CIjq4JDtsENegyDzz5mK/DOQseA4fQLp6akyzldfwnfB6u7GBk8qTVhFrvw8t+JJESEvPsBvs5uU1EKtSQsbZEXdYgYKTpRsYROb6AiuK9xCqmlLoDycSVJWCD0DKmRG9/yBT1kDnGleVQTd0e70r+faVf6LpaO6c+jcNdfczTTh9C/BrlvQPpK6QfizsxUhQrUn2mnXmOxBDVkTqU+P3A8lC01OlILyra0hXKHue9BH5LRd5/5T4zqc9qDnoX3jdbIUDZH0Z/VNF5sRDxfOlQc1fyz6QXQ8bYCBtFQ18BBj54pDgeL99dBYte3jlgDsdlr1HaS2ZbjcmpYbrdWU4KMV9Qe8SfJU6RRl/JqJmNX6bcnkVzXwZONmzpWS8Njc7mxrweufau+c4iwS90AD9UIrcwFZz9hNZIc/LhE+Gc2qYsziWmQzCJTepZrxLwpdQEDIrBTHGEPprySEBtGtfCnV+8ebxp6G91oIXUTr19nODKrIEZItVHFM99TvAtJIA5EYUfVypt9YgjMizkyoima0WalljQpJbyZk3Khhr1gdk65kHxWs8KgBYr4wlIWLAVOGQaCH29j49bWbTA4QNOLC4IUfoTJXyCnEc27z6hrC36lg==,iv:KWldA6a5dEYvUkYIKrucekYwfhtCvYwuBo4zTRLl3D0=,tag:GZNU4JQ8izwA5UxHhfjdCg==,type:str]
sops:
    age:
        - recipient: age16aftwyj928j8j6n2shuugdesppaz5p0r5evgg8888k0ygg70u4qsf7jc37
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTWVVdjlPQXQvanNvcFNK
            LzZmQVozVm9Ka05IaEJpbGxNS1RIamc5VlRzCkE3S01Rd295Nmh4MXhoeWJpaE9q
            NDk2R2piV1FWamZlY1Y1MWRUclFLdTgKLS0tIFp0WCt4VXVVMUQ1dzc0MXA5Q3R2
            d09oS0RZSmd1clJ3SVdEZ2J2bDRmYk0KtrjfPd1ma/Hnhoq8phLfTmRPRTt2EGXY
            Rkm0HFUARlME7WHjuP4AmI1Sujk3kr8nLxI3oIgnaWtCrHpimtHXoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dk40kh8vwhk7lf5qhwmsfh2twmj7gdrkynx20lh4lmar0z4kvqgshkm289
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc21KL0txNW9VWlo4Z044
            dlA1VWE2MlpZYXFvdzlFZVBKSzRYaERZMVJ3CkJwWE1vYXdiUFdQM0NYQzhqUStM
            TG9qMzFuYTRiaG91ZFpNaTYvQjVEMDQKLS0tIEJnZk95NEJGWGVuNkIyMEllSkk1
            cWhtcXdRQjZ6cjNTVk1ZblVIRkRLNXMKuhdQonDsnE0t09yMayj+vl0LAm+sHPGd
            DwTbOFj4aM7dNi4uPOYe+dDmKXLg+HdXhs0ZEjG77rILV+WVGioFfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19ntyr90hwka356y4malera78wytrl6wr6eacwqppyu86eh4p6pdst4qkn4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NE9YWWgwLzRkcFNXL2Yx
            S1JPRk1vdW1acmtmZ1NQZmVKUjZKdyt6N3pVCmxuWWpvZFFLU3o1VFZHK3EvdFJ2
            QXNOZWloWExPbmVYaFc3clBPZnJwSDgKLS0tIDNKUTlwRU9mRU5hZzc0Ny9wVFNE
            dzRxS0dkbFF0bGJBb0R6aEVhTURFb2MKC2f+zEAWgwtYpGJO+T5j6aYkD0YHEKcE
            JrjS1uSW0fwZrP6c48dsRKe1lLvsp95WRiD9QngKQPoOf/NPbyjn6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w9wfp2z6hnnt3yjy733eejy5qv894ml243z4ywyp3txpwvcfmdhqr4rnz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZEdjbm9pM2FOQ3BmTGZQ
            Yk9PRnQ3ZGFxNkRYYTJyMkRxWmhYeXVaUzBFCjl3VkhrL0NqbWN6K2xFQitxWVdV
            VzRVbitCS1UyWG5SRmNVaTJJN0JaMk0KLS0tIGdoZEUvTTZ3am4xY0szWjgxSXE5
            c2JIZzVhc2ZtVjY0YWdiT0cwWEtqcTgKgN1aNk7d9csYsVYxbd/Uyg4A3m4ODIUZ
            ZepXawcFNECu0N2Vd6Ox7y4RxIQrPWhY9mIKb3TxXcEfqvuRmv9KvA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18wwkg4v96ktu7pujcy3jc54j2gd0c3pt8vkup9qj2200dwr6vccsplhn5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWXlweDlySzRWYWVtd2dM
            anN4Q0FEZnpkcUFMR3VoS2Z3bGZwUy9WK0JvCnFLTDdyeEhub25jVXVRRFpVTXFC
            Uk4xUDlXa1lRSXB1WG5oUlB0ak8rK2MKLS0tIHh0NnJtUko5aldELzZ1eldieDFZ
            cFZKVHZpWDZjckdRekxjVW53ODdVM2sKSX8c1YTtRA+y82BJVF6VTroBuktqbili
            VYazIb6VoUOj6NV5msf1Z8UaPLs0/QuY0Fyb1N/OOnk2Rc8lgbhriA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T14:10:21Z"
    mac: ENC[AES256_GCM,data:k8AkaU8jvFgpfETs3W89Dur/aGfdF+eoSqZ/ZA1rRB3F/YLv6o24AZrP/t6h4FXkAHUpz+rttSwcLr3UAuB4BducJmoCH3xAYRd5zAYvBYd1ysypKANlSwEkIxNKXYygJm8LqGWDny8uihgvtmQcNGRpaIzyqC2bu4QkUApmPVE=,iv:rR9u1LetXyiswjYZ4UFOkeahHkiAXn7EIP3tVed+BG8=,tag:bPVjPigdZCQEIFWGXjoZvQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
